name: Deploy components dosc site with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and compile project
        run: |
          npm ci --force
          npm run build

      - name: Build deployment package (excluding node_modules and other directories)
        run: |
          tar -cvf components.tar \
          --exclude='tsconfig.json' \
          --exclude='node_modules' .
          gzip components.tar

      - name: SSH to server and clear
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWD }}
          script: |
            touch test.txt
            mkdir -p /apps/demo
